name: z-all
on:
  workflow_dispatch:
    inputs:
      workflows:
        description: 'workflows'
        required: true
        default: 'grbts jupyter-hub jupyter-lab rbackup strongswan vlmcsd'
        type: string
permissions:
  actions: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      WORKFLOWS: ${{ inputs.workflows }}
    steps:
      - run: |
          set -ex
          for wf in $WORKFLOWS; do
            gh workflow run "$wf.yml" --ref "${{ github.ref_name }}" -f latest=false
          done
